### ISSUE TITLE
Menu closes when you move diagonally slowly

### ISSUE THREAD

**Issue by davidscotson** [orthes/medium-editor-insert-plugin#131]
If you open the menu and move directly towards the second item in the list at a diagonal, the menu closes before you get to the item you want to click on.

It works if you move quickly enough so perhaps there's already a timeout? If so it seems a bit short.

**Comment by orthes** [comment]
Yes, I know about this bug in 0.x version, but since we're preparing 1.0 version which has completely different UI, the 0.x was left a little forgotten.

The problem is not with a timeout. There is none. The problem is with plugin's active space which looks like this:

![screen shot 2015-01-06 at 13 11 11](https://cloud.githubusercontent.com/assets/312938/5628354/31095a76-95a6-11e4-8dc9-02977cf7c664.png)

If you move your cursor out of this space, the plugin will close. So you have to go first to the fist item and then to the second one. If you go diagonally, the menu will close.
