### ISSUE TITLE
Experienced issue using textareas

### ISSUE THREAD

**Issue by NoelBaron** [orthes/medium-editor-insert-plugin#179]
Have you encountered any issues when using medium-editor with textareas? I had no trouble loading up this plugin when using a div, but it would not load if the editor is based on a textarea.

**Comment by orthes** [comment]
medium-editor only recently added support for textareas, but this plugin doesn't support them yet.

What the editor does to support textareas is that it hides a textarea, creates a div and when content of the div changes, the change is reflected to textarea's value.

What you can try now, is to attach the plugin to this newly created div instead of a textarea.

**Comment by NoelBaron** [comment]
I switched to div-mode, it's all good for now.

**Comment by orthes** [comment]
I marked this issue as a bug, because this plugin should support textareas if the editor supports it.

**Comment by unkunus** [comment]
This should not be so difficult to solve, but it took me hours to find what is going on. Many people might be using textareas, and that this is not working maybe shoud be mentioned in the documentation.

For now, it could be enough to use a textarea, let the editor initialize without any additional scripting and just copying the editor div content to the textarea before submitting - editor.serialize() should be used.


	function setTextareaContent (element) {
		content = editor.serialize(); 
		for (var key in content) if (content.hasOwnProperty(key)) break; // getting first json key/value
		element.value = content[key].value;
	}

	editor.on(form, "submit", function(evt){
			setTextareaContent (area);
	}, true);

this does not work if the editor is stopped and then started again with editor.destroy() and editor.setup()
