### ISSUE TITLE
Autoplay html5 videos

### ISSUE THREAD

**Issue by boosis** [orthes/medium-editor-insert-plugin#187]
Is it possible to set autoplay for html5 videos when the page is rendered?

**Comment by orthes** [comment]
No, it's not possible. There would be a problem with that, because videos are covered with overlay layer in editor, so when you're editing you can't play/pause a video. Instead, if you click on a video, you select it and you can set a style or remove the video.

If videos played automatically, you wouldn't be able to stop it in editor.

You could solve it specifically for your project. Before rendering a content you could search for .medium-insert-embed > iframe and add autoplay=1 flag to URLs.
