### ISSUE TITLE
Image Grid logic for different size images

### ISSUE THREAD

**Issue by tauseefk** [orthes/medium-editor-insert-plugin#257]
Hey the image grid doesn't look very good when the images are of different sizes. Can we have a logic in place that would align them in a better way? 
The editor on medium.com aligns a wider image with a taller image and resizes them to make the grid look consistent.

**Comment by orthes** [comment]
The purpose of this plugin is to fit into your website's logic and enable you to use it with another plugins. That's why we don't provide advanced grid solution ourselves. There are many to choose from. You have multiple options how to use them:

1. You can resize images on backend during upload and return to browser a link to the resized thumbnail
2. You can hook it to `uploadCompleted` callback function where you can initialize some sophisticated grid library - for example http://masonry.desandro.com/
