### ISSUE TITLE
Not showing image upload progress bar

### ISSUE THREAD

**Issue by ideadx** [orthes/medium-editor-insert-plugin#264]
Everything works awesome with this plugin! Thanks:)
One issue, I can not get progress bar while image is uploading to server.
Is it inbuilt or do I need more configurations?

**Comment by orthes** [comment]
Progress bar shows only if option `preview` on images addon is set to `false`. But default it is set to `true` which shows preview image instead of progress bar.

**Comment by Eldorado234** [comment]
Hey @orthes, would it be possible to combine both of this?

I could imagine showing the preview picture and a subtle bar below that fills up would be very convenient and still clean in a visual manner. 

Another alternative I have in mind would be to show a global progress somewhere on the page. This would IMHO be even more useful since you are probably interested in the upload of all images instead of the progress of every single one.

**Comment by orthes** [comment]
@Eldorado234 We already have a progress bar on images. You should see semitransparent white overlay on images that serves as progress indicator.

**Comment by Eldorado234** [comment]
@orthes I'm sorry, I didn't recognise that this is a clone of the medium editor 😂 thought medium maintains an open source version of their editor. Cheers.
