### ISSUE TITLE
Trying to use the plugin with Rails

### ISSUE THREAD

**Issue by thiagovelozo** [orthes/medium-editor-insert-plugin#27]
Hi Pavel,

Really great work on the editor. it's really cool. I am using the medium editor with a rails app and it works fine. I added your plugin but it does not work. Do you have any advice for using it with rails? I'm not sure how to connect with the image upload. (I'm using gem 'carrierwave', gem 'mini_magick', for image upload). 

I would really appreciate your help and advice. thank you very much.

**Comment by tezzataz** [comment]
Anyone who has upgraded to the new version, you need to edit the upload function in the controller to something like this:

    def upload
    @picture = Asset.new(image: params[:files].first)
    @picture.save
    url_response = { 
    files:
    [
      {
        url: @picture.image.url
      }
    ]
    }
    render :json => url_response
    end

**Comment by orthes** [comment]
:+1:

**Comment by jomarbarnobal** [comment]
@tezzataz  

Im using Div for medium editor then bind it into content form like this

`<% form @path do |f| %>
  #hide input
   <%= f.hidden_field :content, html: { id: "content" } %> 
    #below is the div for medium `editor`
   <div id="create" data-field-id="content">
     <%= @post.content.try(:html_safe) %>
   </div>
  <%= f.submit %>
<% end %>`

and in my js i bind the input and listen to propertychange event
$('#create').bind 'input propertychange', ->
  $('#post_' + $(this).attr('data-field-id')).val $(this).html()

Its works fine to me but the problem is, the image don not include in propertychange event. So i need to wrap the image with text  to save.

Is there any good approach for this ?

By the way  i use your approach in saving image like this
addons: {
          images: {
          fileUploadOptions: { url: '/admin/posts/upload_image'},
          deleteScript: '/admin/posts/delete_image'  
        }
}
It did save the image but i cant delete it, coz it didn't  find the id
and this is my server response 
{"files":[{"url":"/uploads/attachment/image/19/Nature_Tripping__inset_1_.jpg"}]}

Thanks and advance
