### ISSUE TITLE
How to load data for embeds over HTTPS instead of HTTP.

### ISSUE THREAD

**Issue by rohitpal440** [orthes/medium-editor-insert-plugin#282]
Hello there!
I want to load data from embed links on HTTPS as most of browser blocks the http request on a HTTPS website.
So when I paste a link in embed section it don't get loaded by browser like firefox or chrome. This can work only if we make request to medium.iframe.ly api over https. please help

**Comment by orthes** [comment]
This happens when not using oEmbed? 

I'm looking to the code and we're omitting protocols and using only `//` in embeds, which should work for both HTTP and HTTPS websites: https://github.com/orthes/medium-editor-insert-plugin/blob/master/src/js/embeds.js#L356 

At which point is HTTP link inserted to your website? Can you reproduce the problem on https://jsfiddle.net/?

**Comment by askehansen** [comment]
The issue seems to be when calling medium.iframe.ly
https://github.com/orthes/medium-editor-insert-plugin/blob/fe002ea832dceb9c91e0941b5ccac73d65165258/src/js/embeds.js#L11

Unfortunately it can't be called over https

**Comment by rohitpal440** [comment]
Ok! I've solved this issues by using changing the 
`oembedProxy: 'http://medium.iframe.ly/api/oembed?iframe=1',`
to
`oembedProxy: 'https://medium.iframe.ly/api/oembed?iframe=1'&api_key=<your_api_key>,`
You can get your api key by signing it up to iframe.ly, they offer free 10000 hits per month for developer plans.

**Comment by a-vasyukov** [comment]
better to write in the config:
```javascript
addons: {
    embeds: {
        oembedProxy: 'https://iframe.ly/api/oembed?iframe=1&api_key=<api_key>'
    }
}
```
