### ISSUE TITLE
Add Webpack Support

### ISSUE THREAD

**Issue by JoshZA** [orthes/medium-editor-insert-plugin#299]
Medium-Editor is webpack compatible and published to NPM.

Would be amazing if this plugin was too

Right now we're forced to use https://github.com/joar/medium-editor-insert-plugin which is fairly outdated

**Comment by orthes** [comment]
You're absolutely right. Back in a day when I started this plugin, there was a clear division - bower was used for browsers and npm for nodejs. Since then things definitely changed and we need to be on npm and compatible with webpack and amd...

I'll wrap the plugin into this: https://github.com/umdjs/umd/blob/master/templates/jqueryPlugin.js

**Comment by orthes** [comment]
[v2.3.0](https://github.com/orthes/medium-editor-insert-plugin/releases/tag/2.3.0) was just released and we're finally on npm: https://www.npmjs.com/package/medium-editor-insert-plugin
