### ISSUE TITLE
Adding an image to end of the editable are adds an unremovable paragraph after image

### ISSUE THREAD

**Issue by orhanveli** [orthes/medium-editor-insert-plugin#326]
When I add an image to end of the text in the editable are causes insert an extra paragraph and if you want to remove this p by backspace it removes image that you added too.

What logic we should run for this issue?

**Comment by j0k3r** [comment]
I guess that adding this empty paragraph allow user to continue writing after the image by letting him getting the focus.
But I've no idea why when you remove it, it also remove the image.

Maybe @orthes has a better idea.

**Comment by orthes** [comment]
Exactly like @j0k3r wrote. If you add an image at the very end of the editor, you need to have an extra paragraph created under it in order to be able to continue writing. Without that you would be stuck with the image and no text could be added under it.

And logic behind removing image when pressing backspace in that paragraph is also simple. Say you're writing simple text in any text editor, even simple textarea. Write a few paragraphs and then place caret at the beginning of one paragraph. Now hit backspace. What it does? Does it delete that paragraph? No, it deletes a character to the left of the caret.

In case of MediumEditor, to the left of the caret is image, thus it's gets deleted.
