### ISSUE TITLE
Embeds in 3.0?

### ISSUE THREAD

**Issue by jbrozena22** [orthes/medium-editor-insert-plugin#332]
Hi, just wondering if there were any plans on adding the youtube/vimeo/etc embed code to the 3.0 branch? I really love the lack of dependencies in 3.0, but as of now there are only placeholders for the embed code.

I tried seeing if it could be easily ported over from the 2.3 version, but it appears 3.0 is a complete overhaul with completely different javascript styling.

Let me know! Thanks.

**Comment by orthes** [comment]
Hey @jbrozena22! I'm happy that you love the new 3.0 approach. As you know, programming style and skills evolve by time, but when you have an open source project, sometimes it's hard to keep up with the latest trends and knowledge and remain backwards compatible at the same time. That's why I decided to completely rewrite the plugin, because it's easier than to just refactor.

Sadly, I haven't had much time recently not only for the 3.0 branch, but for open source in general. But I have one project coming that I would like to use the new 3.0 version on, so I'll try to find some time and finish at least basic functionality for images and embeds.
