### ISSUE TITLE
on click add image in medium editor insert image

### ISSUE THREAD

**Issue by ramtml** [orthes/medium-editor-insert-plugin#340]
First of all Thx for the great plugin.

And i would like to add an image when user click on a div. How could i achieve this ?? Is it possible to do with medium editor js??

Also i would like to upload an image from editor tool bar too...

**Comment by orthes** [comment]
This is not possible right now. But you can do it yourself. Just listen for clicks on divs and fire clicking on plugin buttons yourself. Something like this:

```javascript
$(document).on('click', 'div', function (e) { 
  $('a[data-addon="images"]').click(); 
});
```

This is super basic example. You will have to make sure that the div that you want to upload images to has `.medium-insert-active` class, because that's how the plugin knows what is the active element.

For uploading from toolbar you will have to create your own button that would do the same - https://github.com/yabwe/medium-editor/tree/master/src/js/extensions#what-is-a-button
