### ISSUE TITLE
Align in 3.0

### ISSUE THREAD

**Issue by injectless** [orthes/medium-editor-insert-plugin#343]
Hi everyone,
Does the 3.0 works?

![screenshot_2016-07-02_11-07-40](https://cloud.githubusercontent.com/assets/12424545/16540735/4bd23cd8-4045-11e6-941d-392426648d10.png)

### This is what it does:

- [x] Add image (the image appends always in the center, with figure tags)
- [ ] Align the image (it shows the buttons, but they do nothing)
- [ ] Youtube Video -> Embeds. The icon to add it is there, tho it just throws a log console.

Cannot figure it out how to allign the images. With just that I'm free to go for now.
Thanks, I wasn't using the plugin for all the plugins it contains (beautiful functions, too much code), 'till I saw this. Even more awesome.

**Comment by orthes** [comment]
Hi @injectless. I see that you discovered our 3.0 branch. Unfortunately, v3.0 is not ready. As you can see in releases, v3.0 has not been released yet. So the branch you've discovered is just a work in progress.

What is done is basic scaffolding for the rest of the extension, image uploading, basic toolbar that doesn't work yet and placeholder for embeds.

So you've pretty much found what it does so far.

**Comment by injectless** [comment]
Wait!

Just, please.. give me a hint, something to just make the toolbar for align the image work, that's all I ask. I will love you forever.

```
 buttons: [{
	                    name: 'align-left',
	                    action: 'left',
	                    label: 'Izq'
	                }, {
	                    name: 'align-center',
	                    action: 'center',
	                    label: 'Ctr'
	                }, {
	                    name: 'align-right',
	                    action: 'right',
	                    label: 'Der'
	                }]

```
Now, I guess the selected image adds a class somewhere ¿?

**Comment by nmielnik** [comment]
@injectless assuming that this plugin isn't doing anything to change what happens when toolbar buttons are clicked, if you're just overriding these options in buttons, the click of the button will be handled [here](https://github.com/yabwe/medium-editor/blob/master/src/js/extensions/button.js#L163-L172).

If you don't override it, it will ultimately call `execAction()` with the value of the `action` property you defined here (ie 'left', 'center', 'right').  This will then call `execActionInternal` on the editor itself (code [here](https://github.com/yabwe/medium-editor/blob/master/src/js/core.js#L540-L596)) which will try to have the browser handle it via `document.execCommand('action')`.  This won't do anything, as the browser would only understand `justifyLeft`, `justifyCenter`, `justifyRight`, and `justifyFull`.  If you use those justify actions instead of your 'left', 'center', 'right' actions, what happens?

If you want to fiddle around with adding a class or what-not, I would start just by overriding the `handleClick` method and see if you can do something there.  You can override it by passing it as an additional property to 'name', 'action', and 'label':

```js
buttons: [{
    name: 'align-left',
    action: 'left',
    label: 'Izq',
    handleClick: function (evt) {
        // do your thing here
    }
}];
```

**Comment by anorudes** [comment]
Hello, you can use this fork https://github.com/anorudes/medium-editor-embed-plugin. Here there is, showing the loader, upload through third-party widgets, adding a description to the image.
I made it a separate repository, because I do not know whether the author will accept these changes to himself
