### ISSUE TITLE
Integrate the plugin with angular(angular2) application

### ISSUE THREAD

**Issue by saiyaff** [orthes/medium-editor-insert-plugin#412]
Folks,
Is there any way to integrate this with an angular2 application? I was using some wrappers suggested in the   'wrappers and integration' section. Clueless about how to do it with an angular2 application developed using angular-cli

**Comment by msaiyaff** [comment]
Actually followed the integration methodology suggested in the documentation since without using jquery I couldn't move on to integrate this. Then, I am getting this error on initializing step at the basic integration itself.
`$(function () {
      $('.editable').mediumInsert({
        editor: this.editor
      });
    });`
Error as here - ` Property 'mediumInsert' does not exist on type 'JQuery'`

**Comment by msaiyaff** [comment]
@orthes Any help or any support would be appreciated!

**Comment by julpane** [comment]
+1
I want implement on angular to.

**Comment by saiyaff** [comment]
@julpane Have a look at [quilljs](https://github.com/quilljs/quill) and [ngx-quill](https://github.com/KillerCodeMonkey/ngx-quill)
Since this plugin is totally based on jquery I reckon you not to integrate this with an angular application.
