### ISSUE TITLE
Embed videos are not reproducible

### ISSUE THREAD

**Issue by wenderjean** [orthes/medium-editor-insert-plugin#464]
Why embed videos are not reproducible? There is a div `medium-insert-embeds-overlay` that not allow videos to be reproduced.

Why that `div` exists?

![screen shot 2018-05-21 at 17 02 35](https://user-images.githubusercontent.com/941776/40327376-070e905e-5d19-11e8-8b6e-c8ecb799a778.png)

**Comment by orthes** [comment]
Our demo page is showing you an editor side of things. In editor videos are not playable, because you need to be able to select them instead.

But when you save the serialized content (`editor.serialize()`) it will get rid of this overlay div and then when you use this HTML on your "show" side, the video will be playable for your visitors.
